### ISSUE TITLE
UT Windows bug

### ISSUE THREAD

**Issue by ydoc5212** [biglocalnews/warn-scraper#201]
Traceback (most recent call last):
  File "C:\Users\Cody-DellXPS\WARN\warn\cli.py", line 67, in main
    runner.scrape(state)
  File "C:\Users\Cody-DellXPS\WARN\warn\runner.py", line 46, in scrape
    output_csv = state_mod.scrape(self.output_dir, self.working_dir)
  File "C:\Users\Cody-DellXPS\WARN\warn\scrapers\ut.py", line 43, in scrape
    writer.writerows(output_rows)
  File "c:\users\cody-dellxps\appdata\local\programs\python\python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 42-43: character maps to <undefined>

**Comment by palewire** [comment]
This scraper is now running fine for me. Since this ticket is over six month old, I'm going to close it. If you are still affected by the error please speak up. We can always reopen.

**Comment by Dilnaz-N** [comment]
I have come across the same error. Is there a solution to fix this?

**Comment by stucka** [comment]
@Dilnaz-N and @ydoc5212 , can you try `pip install --upgrade warn-scraper` and then verify everything's working for you? I think you've highlighted a significant flaw in the workflow here that I've flagged as Issue #584 . If you have any problems, please comment again and I'll reopen.

To be honest I'm doing development work on this stuff but gave up with both Windows and WSL because some of the assumptions in this and cousin projects made it nigh impossible, and now I do just about everything in a virtual machine, which ... adds a bunch of friction. Thank you for flagging this.

**Comment by Dilnaz-N** [comment]
Thank you @stucka . The error is no longer appearing.
