### ISSUE TITLE
Handle if missing directory

### ISSUE THREAD

**Issue by stucka** [biglocalnews/warn-scraper#320]
I may not be understanding your philosophy here, but I think possibly **warn/utils.py** could benefit from some os.makedirs calls because there are assumptions about directories that may not yet exist. A potential fix:

```
for localdir in [WARN_CACHE_DIR, WARN_DATA_DIR, WARN_LOG_DIR]:
    os.makedirs(localdir, exist_ok=True)

```

From a clean install:
(warn-scraper-n_JOXqYy) C:\data\warn-scraper>python
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from warn.scrapers import fl
>>> fl.scrape()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\data\warn-scraper\warn\scrapers\fl.py", line 71, in scrape
    output_csv, CSV_HEADERS, output_rows, extrasaction="ignore"
  File "C:\data\warn-scraper\warn\utils.py", line 58, in write_dict_rows_to_csv
    with open(output_path, mode, newline="") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mstucka\\.warn-scraper\\exports\\fl.csv'

**Comment by palewire** [comment]
I might be missing your point, but I think this is handled in our runner. https://github.com/biglocalnews/warn-scraper/blob/main/warn/runner.py#L32-L35

**Comment by zstumgoren** [comment]
hey @stucka - Yep, as @palewire mentions, the Runner handles directory creation in certain default locations in the CLI context. If you're importing the library for use in a custom script, then the user is on the hook for specifying and creating dirs for cache, exports etc. At least that's the general approach -- I certainly can't claim the status of a philosophy! -- we applied when we first started efforts to standardize this code base before opening it to the public. We have a ways to go, but @palewire just came on board and is helping us polish this thing up quite a bit! 

It's quite possible a scraper or two *does* auto-create dirs, so that may be something we should look out for during current standardization efforts. Probably worth mentioning this general approach in the README or docs to avoid confusion going forward (sorry about that omission -- that's a fail on my part!)

**Comment by stucka** [comment]
Seems like individual calls to the scrapers as a libraries are running through warn/utils.py that adding in the directory creation there isn't going to cause problems. I can submit a PR if y'all desire, or just leave it be. Not a huge deal either way, but does prevent the thing from being used directly as explained in the docs.

**Comment by palewire** [comment]
Ah ha! Now I'm catching up and see the bug. I think I'd take that PR. The paranoid part of my brain wonders if there's some downside to creating directories when a file is imported. I wonder if we should maybe have some kind of check in the write functions, where they could be "lazily" created.
