### ISSUE TITLE
Integrate scrape metadata into code files

### ISSUE THREAD

**Issue by palewire** [biglocalnews/warn-scraper#327]
We've got a [great spreadsheet](https://docs.google.com/spreadsheets/d/1rQ_PMQZbwQQxBRDCIzBbIJrsiI6JraoYoEWrCvDZMe8/edit#gid=1679145335) where we're storing metadata about our scrapes. My proposal is that we write these values into the Python as `__` values at the top of each file. Those values could then be published in our [dashboard table](https://warn-scraper.readthedocs.io/en/latest/sources.html) in the docs via our [automated doc generator](https://github.com/biglocalnews/warn-scraper/blob/main/setup.py#L53-L105).

The table would give us everything the spreadsheet does. By integrating the metadata into the repository we wouldn't have to keep up a separate sheet, which is less work, and we'd be able to more closely monitor changes.

**Comment by zstumgoren** [comment]
@palewire One question to consider -- for the `__authors__` dunder var, should we use GH contributor usernames instead of actual names? Or perhaps both? That could let us link to the contributor home pages using our auto-doc generators. So a convention such as `__authors__ = 'Ben Welsh:palewire,Dilcia Mercedes:dilcia19'` etc.?

**Comment by palewire** [comment]
Gotcha. Maybe just a list and not a string, too.

**Comment by palewire** [comment]
This has been superseded by #334 and #335
